MINGW_DIR="C:/MinGW"
GPP=wine "${MINGW_DIR}"/bin/mingw32-g++
WINDRES=wine "${MINGW_DIR}"/bin/windres
FLAGS=-s
EXT_FLAGS=-static-libgcc -static-libstdc++

all: ../bin ../bin/updatem.exe ../bin/runner.exe ../bin/shellexecute.exe ../bin/lsdeps.exe ../log.exe
	$(MAKE) -f Makefile.wine -C complement
	$(MAKE) -f Makefile.wine -C img_viewer

clean:
	rm -f ../temp/xmlres.o ../bin/updatem.exe ../bin/runner.exe ../bin/shellexecute.exe ../bin/lsdeps.exe ../log.exe
	$(MAKE) -f Makefile.wine -C complement clean
	$(MAKE) -f Makefile.wine -C img_viewer clean

../temp:
	mkdir ../temp

../bin:
	mkdir ../bin

../temp/xmlres.o: ../temp manifest.xml xmlres.rc
	${WINDRES} -i xmlres.rc -o $@

../bin/lsdeps.exe: lsdeps.cpp itlib.cpp itlib.h peliberr.cpp peliberr.h stdafx.h
	${GPP} ${FLAGS} -static-libgcc -O2 lsdeps.cpp itlib.cpp peliberr.cpp  -o $@

../bin/runner.exe: runner.cpp
	${GPP} ${FLAGS} ${EXT_FLAGS} -O3 runner.cpp -o $@

../bin/shellexecute.exe: shellexecute.cpp
	${GPP} -s -O0 -mwindows shellexecute.cpp -o $@

../bin/updatem.exe: updatem.cpp zockets.cpp zockets.h ../temp/xmlres.o
	${GPP} ${FLAGS} -O0 -mwindows updatem.cpp zockets.cpp -lwsock32 ../temp/xmlres.o -o $@

../log.exe: log-w32.cpp
	${GPP} ${EXT_FLAGS} -mwindows log-w32.cpp -o $@
