WX_CONFIG=wx-config
GPP=g++
CXXFLAGS=-O2 -std=c++14 `${WX_CONFIG} --cxxflags`
LDFLAGS=`${WX_CONFIG} --libs`
OBJS_DIR=../../temp/complement/release.mac

all: ../../bin/complement.bin ../../bin/complement_wrap.bin

include Makefile.common

clean:
	rm -rf ${OBJS} ../../bin/complement.bin ../../bin/complement_wrap.bin
	rm -f core

../../bin/complement.bin: ${OBJS_DIR} ${OBJS}
	${GPP} ${OBJS} ${LDFLAGS} -o $@

../../bin/complement_wrap.bin: complement_wrap.cpp
	${GPP} complement_wrap.cpp -O2 -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}
