WX_CONFIG=wx-config
GPP=g++
CXXFLAGS=-O2 -std=c++14 `${WX_CONFIG} --cxxflags std,aui,stc,richtext,html`
LIBS=`${WX_CONFIG} --libs std,aui,stc,richtext,html`
OBJS_DIR=../release.mac

all: ../zinjai

include Makefile.common

clean:
	rm -rf ${OBJS} ../zinjai

../zinjai: ${OBJS}
	${GPP} ${OBJS} ${LIBS} -o $@

${OBJS_DIR}:
	mkdir ${OBJS_DIR}
